name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main  # Adjust if your default branch is different

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub repository
        uses: actions/checkout@v2

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_GREEN_FOREST_010F03D00 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: 'upload'                 # Ensure this is included
          app_location: '/'                # Path to your HTML files
          output_location: '/'             # No build output folder
          app_build_command: ''            # Skip build step
