name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main  # Change to your default branch if needed

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub repository
        uses: actions/checkout@v2

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          app_location: '/'             # Path to your HTML files
          output_location: '/'          # No build output folder
          app_build_command: ''         # Skip build step
